title: 'Das co-kreative Netzwerk'
author:
  name: 'Das co-kreative Netzwerk'
  email: 'info@dckn.de'
metadata:
    description: 'Das co-kreative Netzwerk wurde 2023 gegründet mit dem Ziel co-kreative Projekte zu fördern.'
