services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./user:/config/www/user
    ports:
      - "8080:80"
    restart: unless-stopped
